### ISSUE TITLE
Feature: update to support GHC-9.x

### ISSUE THREAD

**Issue by mouse07410** [phoityne/hdx4vsc#20]
It would be **outstanding** if Phoityne could support the current GHC (9.0.2, 9.2.4, 9.4.2) for debugging. 

That's the only thing I'm missing from a good Haskell IDE!

Thank you!

**Comment by mouse07410** [comment]
Thank you!

I'm using Cabal with GHC-9.2.4 and 9.4.2 on MacOS, with VS Code.

Installed ghci-dap, haskell-debug-adapter, phoityne-vscode. 

Was unable to run debug, though breakpoint got set successfully - something was waiting forever fire GHCI prompt. Works appreciate any help!

**Comment by phoityne** [comment]
Could you show me the VSCode terminal log?
(debugging with ghc-9.2.4)

**Comment by mouse07410** [comment]
Debug console:
```
Configuration read.
Starting GHCi.
Wait for a moment.

CWD: /Users/ur20980/src/stepic-tests
CMD: cabal exec -- ghci-dap --interactive -i -i/Users/ur20980/src/stepic-tests

Now, waiting for an initial prompt("λ> ") from ghci.
```

`.vscode/phoityne.log` is empty at this point. After quitting the debugging session, `.vscode/phoityne.log` contains
```
2022-09-08 23:09:27.384928000000 [5018(ThreadId 24)] CRITICAL REQUEST - invalid HANDLE. eof.
```

After manually starting GHCI in a terminal window (not in VS Code):
```
$ ghci
.  .  .
Loaded GHCi configuration from /Users/ur20980/.ghc/ghci.conf
λ> 
```

**Comment by mouse07410** [comment]
When quitting the debugging session (which appears frozen anyway), I get a popup from VS Code:
```
Timeout after 2000 ms for 'terminate'
```

**Comment by phoityne** [comment]
Hi.
I have reproduced this issue with your ghc config.
When I made the following changes, it worked. (on Linux)
```
[phoityne@localhost .ghc]$ pwd
/home/phoityne/.ghc
[phoityne@localhost .ghc]$ diff ghci.conf.issue ghci.conf
1c1
< :set prompt "\ESC[38;5;208m\STXλ>\ESC[m\STX "
---
> :set prompt "λ> "
[phoityne@localhost .ghc]$ 
```

But now I can't set breakpoints.
continue to investigate.

```
H>>= :dap-set-breakpoints ...
H>>= [ERROR][APP] <command line>: module 'Main' is not interpreted; try ':add *Main' first
:dap-continue ...
```

**Comment by mouse07410** [comment]
> When I made the following changes, it worked. (on Linux)

The change you showed drops setting color to "λ> " prompt.

> But now I can't set breakpoints. 

Yes, I concur - when I change `~/.ghc/ghci.conf` to stop colorizing the "λ> " prompt, GHCI starts, and runs the executable from start to finish, ignoring the breakpoints.

> Continue to investigate.

Thank you! (And maybe it would get support for 9.4 working too? ;-)

Oh, the log file now contains
```
2022-09-14 22:52:48.786466000000 [59169(ThreadId 25)] ERROR APP - [CRITICAL] can not get the initial ghci prompt.
2022-09-14 22:55:46.162988000000 [59555(ThreadId 25)] ERROR APP - [CRITICAL] can not get the initial ghci prompt.
2022-09-14 22:58:42.757139000000 [64749(ThreadId 25)] ERROR APP - user error (<getModule> loaded module can not find from path. </Users/ur20980/src/stepic-tests/src/Board.hs> [("Main","/Users/ur20980/src/stepic-tests/app/Main.hs")])
```

**Comment by phoityne** [comment]
It works when setting color control chars in the launch.jason as below
```
"ghciInitialPrompt": "^[[38;5;208m^Bλ>^[[m^B",

 with vi, you can input control chars by this command.
  ^[   -->  :r! echo -e "\x1B"
  ^B   -->  :r! echo -e "\x02"
```
or, simply  set ">".

> But now I can't set breakpoints.

This is a behavior of the ghci with "-fobject-code" option.
https://downloads.haskell.org/~ghc/9.4.2/docs/users_guide/ghci.html#ghci-obj
```
$ cat /etc/redhat-release
CentOS Stream release 9
$
$ cabal exec -- ghci --interactive -i -i/work/haskell/sample-cabal
Loaded package environment from /work/haskell/sample-cabal/dist-newstyle/tmp/environment.-99525/.ghc.environment.x86_64-linux-9.4.2
GHCi, version 9.4.2: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/phoityne/.ghc/ghci.conf
λ> :load /work/haskell/sample-cabal/app/Main.hs
Ok, one module loaded.
λ>:module Main
λ>:break Main 7 0
module 'Main' is not interpreted; try ':add *Main' first
λ>:add *Main

<no location info>: error: module ‘Main’ cannot be found locally
Failed, no modules loaded.
λ>:q
Leaving GHCi.
$
```

After updating the source code and
without "-fobject-code" option, it works.

```
$ cabal exec -- ghci --interactive -i -i/work/haskell/sample-cabal
Loaded package environment from /work/haskell/sample-cabal/dist-newstyle/tmp/environment.-100050/.ghc.environment.x86_64-linux-9.4.2
GHCi, version 9.4.2: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/phoityne/.ghc/ghci.conf
λ> :load /work/haskell/sample-cabal/app/Main.hs
[1 of 2] Compiling Main             ( /work/haskell/sample-cabal/app/Main.hs, interpreted ) [Source file changed]
Ok, one module loaded.
λ> :module Main
λ> :break Main 7 0
Breakpoint 0 activated at /work/haskell/sample-cabal/app/Main.hs:(4,8)-(9,30)
λ>:q
Leaving GHCi.
$ 
```

Regards.

**Comment by mouse07410** [comment]
Thank you very much for investigating this problem and finding s solution!

> After updating the source code and
without "-fobject-code" option, it works.

By "source code" you mean "my code that I'm debugging", not "GHCi source code", right?

I don't think I'm setting "-fobject-code" explicitly. How can I "unset" it through GHCi configuration file (or in Cabal invocation of GHCi)?

**Comment by mouse07410** [comment]
Also, attempting to re-install ghci-dap:
```
$ cabal install haskell-dap ghci-dap haskell-debug-adapter phoityne-vscode --overwrite-policy=always
.  .  .
Failed to build exe:ghci-dap from ghci-dap-0.0.17.0.
Build log ( /Users/ur20980/.cabal/logs/ghc-9.4.2/ghc-dp-0.0.17.0-6d3351ba.log
):
Configuring executable 'ghci-dap' for ghci-dap-0.0.17.0..
Preprocessing executable 'ghci-dap' for ghci-dap-0.0.17.0..
Building executable 'ghci-dap' for ghci-dap-0.0.17.0..
[1 of 6] Compiling GHCi.DAP.Constant ( app/GHCi/DAP/Constant.hs, dist/build/ghci-dap/ghci-dap-tmp/GHCi/DAP/Constant.dyn_o )
[2 of 6] Compiling GHCi.DAP.Type    ( app/GHCi/DAP/Type.hs, dist/build/ghci-dap/ghci-dap-tmp/GHCi/DAP/Type.dyn_o )

app/GHCi/DAP/Type.hs:10:1: error:
    Could not find module ‘GHCi.GhcApiCompat’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
10 | import qualified GHCi.GhcApiCompat as GAC
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[5 of 6] Compiling Paths_ghci_dap   ( dist/build/ghci-dap/autogen/Paths_ghci_dap.hs, dist/build/ghci-dap/ghci-dap-tmp/Paths_ghci_dap.dyn_o )
Error: cabal: Failed to build exe:ghci-dap from ghci-dap-0.0.17.0. See the
build log above for details.
```

**Comment by mouse07410** [comment]
### Update
On the installed `ghci-dap` compiled with GHC-9.2.4, **debugging worked when I reset default GHC to 9.2.4**.

As most of my stuff now is on GHC-9.4.2 - **how can I make this debugger work with GHC-9.4.2**?

Thanks!

**Comment by mouse07410** [comment]
### Update 2
Cloned your "haskell-dap" and "ghci-dap", built and installed with GHC-9.4.2.

It works, except for some strange error related to loading dependencies:
```
Configuration read.
Starting GHCi.
Wait for a moment.
CWD: /Users/ur20980/src/stepic-tests
CMD: cabal exec -- ghci-dap --interactive -i -i/Users/ur20980/src/stepic-tests

Now, waiting for an initial prompt("λ> ") from ghci.

Resolving dependencies...
[DAP][INFO] start ghci-dap-0.0.18.0.
Loaded package environment from /Users/ur20980/src/stepic-tests/dist-newstyle/tmp/environment.-60423/.ghc.environment.x86_64-darwin-9.4.2
GHCi, version 9.4.2: https://www.haskell.org/ghc/  :? for help
package flags have changed, resetting and loading new packages...
Loaded GHCi configuration from /Users/ur20980/.ghc/ghci.conf
λ>:set prompt "<<DAP_CMD_END2>>\nH>>= "
H>>= :set prompt-cont "<<DAP_CMD_END2>>\nH>>= "
H>>= :dap-launch ...
H>>= :load /Users/ur20980/src/stepic-tests/app/Main.hs
[1 of 2] Compiling Main             ( /Users/ur20980/src/stepic-tests/app/Main.hs, interpreted )
Ok, one module loaded.
H>>= :dap-context-modules ...
H>>= :dap-set-breakpoints ...
Breakpoint 0 activated at /Users/ur20980/src/stepic-tests/app/Main.hs:228:3-13
H>>= :dap-set-function-breakpoints ...
H>>= :dap-continue ...
Start run

factorial 28 = 304888344611713860501504000000

sum3squares 1 2 3 = 14

doItYourself log2( (max 42, x)^3) where x = 100 : 19.931568569324174

goSum 15 = (120,())

foldl (+) 0 [0..15] = 120
Stopped in Main.main, /Users/ur20980/src/stepic-tests/app/Main.hs:228:3-13
_result :: IO () = _
227    print $ foldl (+) 0 [0 .. 15]
228    putStrLn ""
       ^^^^^^^^^^^
229    putStr "sum [0..15] = "
H>>= :dap-stacktrace ...
-1  : main (/Users/ur20980/src/stepic-tests/app/Main.hs:227:11-31)
-2  : main (/Users/ur20980/src/stepic-tests/app/Main.hs:227:3-31)
-3  : main (/Users/ur20980/src/stepic-tests/app/Main.hs:226:3-33)
-4  : main (/Users/ur20980/src/stepic-tests/app/Main.hs:225:3-13)
-5  : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-6  : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-7  : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-8  : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-9  : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-10 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-11 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-12 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-13 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-14 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-15 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-16 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-17 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-18 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-19 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:187:31-40)
-20 : mySum (/Users/ur20980/src/stepic-tests/app/Main.hs:186:15-17)
...
H>>= :dap-scopes ...
H>>= :dap-variables ...
H>>= :dap-variables ...
<interactive>: ^^ Could not load '_ghczmprim_GHCziPrimopWrappers_seq_closure', dependency unresolved. See top entry above.

H>>=
```

Note, that everything on my system is built "dynamic". From `~/.cabal/config`:
```yaml
shared: True
executable-dynamic: True
```

**Comment by phoityne** [comment]
Thanks for the invitation.
I have reproduced this issue.
It occurs when you open GHCi Global subtree in the variables pane. 

Continue to investigate.
Regards.

**Comment by mouse07410** [comment]
Also, when I put a breakpoint somewhere (doesn't really matter where) in the `main` function and start debugging - I do not get any output. To replicate, place breakpoint, e.g., on line 600 in the `app/Main.hs` and start debugging. There should be a ton of output on the terminal from all the `putStrLn` and such - but there's literally _nothing_. In the "Local" window I only see `_:result:_` and nothing more. "Global" - you already replicated the problem.

This is with the latest released `phoityne-vscode`, and the current master of `haskell-dap` and `ghci-dap`, GHC-9.4.2, Cabal-3.8.1.0, current/latest released VS Code.

**Comment by mouse07410** [comment]
@phoityne any updates?

**Comment by phoityne** [comment]
```
H>>= :dap-variables ...
<interactive>: ^^ Could not load '_ghczmprim_GHCziPrimopWrappers_seq_closure', dependency unresolved. See top entry above.

H>>=
```
Hi.
This error message is shown by ghci.
You can see it on "seq" of Global scope variables.
I don't know can do or shoule do something to the ghci-dap.


```
GHC.Linker.Loader.loadName
During interactive linking, GHCi couldn't find the following symbol:
  ghczmprim_GHCziPrimopWrappers_seq_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please report this as a GHC bug:
  https://www.haskell.org/ghc/reportabug
```

Actualy, its occurs when ghci-dap calls "pprTypeAndContents" below.
  https://hackage.haskell.org/package/ghc-9.4.2/docs/GHC-Runtime-Debugger.html


Tried "-L" ,"-l" options, but not solved.

```
"ghciCmd": "cabal exec -- ghci-dap --interactive -i -i${workspaceFolder} -L/home/phoityne/.ghcup/ghc/9.4.2/lib/ghc-9.4.2/lib/x86_64-linux-ghc-9.4.2 -lHSghc-prim-0.9.0-ghc9.4.2",
```


```
[DAP][INFO] start ghci-dap-0.0.19.0.
Loaded package environment from /work/haskell/sample-cabal/dist-newstyle/tmp/environment.-30547/.ghc.environment.x86_64-linux-9.4.2
GHCi, version 9.4.2: https://www.haskell.org/ghc/  :? for help
<command line>: user specified .o/.so/.DLL could not be loaded (/home/phoityne/.ghcup/ghc/9.4.2/lib/ghc-9.4.2/lib/x86_64-linux-ghc-9.4.2/libHSghc-prim-0.9.0-ghc9.4.2.so: undefined symbol: stg_upd_frame_info)
Whilst trying to load:  (dynamic) /home/phoityne/.ghcup/ghc/9.4.2/lib/ghc-9.4.2/lib/x86_64-linux-ghc-9.4.2/libHSghc-prim-0.9.0-ghc9.4.2.so
Additional directories searched:   /home/phoityne/.ghcup/ghc/9.4.2/lib/ghc-9.4.2/lib/x86_64-linux-ghc-9.4.2
```

**Comment by mouse07410** [comment]
@phoityne I tried to install `phoityne-vscode` (version from Hackage) with GHC-9.2.5:
```
$ cabal install phoityne-vscode -w ghc-9.2.5 --overwrite-policy=always
Resolving dependencies...
Build profile: -w ghc-9.2.5 -O1
In order, the following will be built (use -v for more details):
 - lens-5.2 (lib) (requires build)
 - regex-posix-0.96.0.1 (lib) (requires build)
 - regex-compat-0.95.2.1 (lib) (requires build)
 - MissingH-1.5.0.1 (lib) (requires build)
 - phoityne-vscode-0.0.28.0 (exe:phoityne-vscode) (requires build)
Starting     regex-posix-0.96.0.1 (lib)
Starting     lens-5.2 (lib)
.  .  .
[104 of 107] Compiling Phoityne.VSCode.TH.SetBreakpointsResponseJSON ( app/Phoityne/VSCode/TH/SetBreakpointsResponseJSON.hs, dist/build/phoityne-vscode/phoityne-vscode-tmp/Phoityne/VSCode/TH/SetBreakpointsResponseJSON.dyn_o )
[105 of 107] Compiling Phoityne.VSCode.Core ( app/Phoityne/VSCode/Core.hs, dist/build/phoityne-vscode/phoityne-vscode-tmp/Phoityne/VSCode/Core.dyn_o )

app/Phoityne/VSCode/Core.hs:2762:41: error:
    Not in scope: ‘FSN.confDebounce’
    Module ‘System.FSNotify’ does not export ‘confDebounce’.
     |
2762 |   FSN.withManagerConf FSN.defaultConfig{FSN.confDebounce  = FSN.Debounce 1} $ \mgr -> do
     |                                         ^^^^^^^^^^^^^^^^

app/Phoityne/VSCode/Core.hs:2762:61: error:
    Not in scope: data constructor ‘FSN.Debounce’
    Module ‘System.FSNotify’ does not export ‘Debounce’.
     |
2762 |   FSN.withManagerConf FSN.defaultConfig{FSN.confDebounce  = FSN.Debounce 1} $ \mgr -> do
     |                                                             ^^^^^^^^^^^^
Error: cabal: Failed to build exe:phoityne-vscode from
phoityne-vscode-0.0.28.0. See the build log above for details.
```

Would you know what the problem is, or how to remedy it? Thanks!

**Comment by phoityne** [comment]
Hi.

You don't need to install phoityne-vscode, follow this installation.

```
$ cabal update
$
$ cabal install ghci-dap haskell-debug-adapter
$
```

Regards.

**Comment by mouse07410** [comment]
Do you recommend that I should remove the currently-installed VS Code "phoityne-vscode", and only rely upon `ghci-dap` and `haskell-debug-adapter`? Will one of them provide the integtation between VS Code and GHCi? I mean - will make your debugger accessible from VS Code?

**Comment by phoityne** [comment]
Yes,
VS Code "phoityne-vscode(extension)" runs "haskell-debug-adapter(bin)".
"haskell-debug-adapter(bin)" runs "ghci-dap(bin)".

Current implementation does not use "phoityne-vscode(bin)".
"phoityne-vscode" hackage package is old one,
 it was renamed to "haskell-debug-adapter" hackage package.

*(bin) means executable binary.
